language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script: 
  - yarn build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-histpry: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit-message: "Deploy Release"
  on:
    banch: master
